# Generated by Django 3.1.3 on 2021-02-14 10:51

from django.db import migrations, models
import django.db.models.deletion
import tv.models
import tvsmashup.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='TVImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to=tv.models.image_path_handler, validators=[tvsmashup.validators.FileValidator(content_types=('image/jpeg', 'image/png', 'image/gif', 'image/tiff', 'application/x-empty'), max_size=5120000)])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.tvshow')),
            ],
        ),
    ]
