# Generated by Django 3.1.3 on 2021-02-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tvshow',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
