# Generated by Django 3.1.3 on 2021-02-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_auto_20210214_1143'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tvimage',
            constraint=models.UniqueConstraint(fields=('show',), name='unique_tvimage'),
        ),
    ]
