# Generated by Django 3.1.3 on 2021-02-14 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_auto_20210214_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmashUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show1', to='tv.tvshow')),
                ('show_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show2', to='tv.tvshow')),
            ],
            options={
                'unique_together': {('show_1', 'show_2')},
            },
        ),
    ]
