# Generated by Django 3.1.3 on 2021-02-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0004_smashup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smashup',
            unique_together={('show_1', 'show_2'), ('show_2', 'show_1')},
        ),
    ]
