# Generated by Django 3.1.3 on 2021-02-19 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0007_category_categoryscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='smashup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tv.smashup'),
            preserve_default=False,
        ),
    ]
