# Generated by Django 3.1.3 on 2021-02-22 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0010_auto_20210222_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryscore',
            name='category',
        ),
        migrations.AddField(
            model_name='categoryscore',
            name='categorysmashup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tv.categorysmashup'),
            preserve_default=False,
        ),
    ]
