# Generated by Django 3.1.3 on 2021-02-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0011_auto_20210222_0714'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categoryscore',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_category_score_user'),
        ),
    ]
