# Generated by Django 3.1.3 on 2021-02-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0013_auto_20210222_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryscore',
            name='rating',
        ),
        migrations.CreateModel(
            name='ShowRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.tvshow')),
            ],
        ),
        migrations.AddField(
            model_name='categoryscore',
            name='show_1_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show_1_rating', to='tv.showrating'),
        ),
        migrations.AddField(
            model_name='categoryscore',
            name='show_2_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show_2_rating', to='tv.showrating'),
        ),
    ]
