# Generated by Django 3.1.3 on 2021-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xb2a41e5f95e0d60ad262319849a3abed', max_length=128),
        ),
    ]
