# Generated by Django 3.1.3 on 2021-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210214_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xd152f0559f10974c2138050a5d0f85d1', max_length=128),
        ),
    ]
