# Generated by Django 3.1.3 on 2021-02-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210214_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xedebb5ed2384fe7128433e42ec3b9aee', max_length=128),
        ),
    ]
