# Generated by Django 3.1.3 on 2021-02-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210214_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xffddbbf982aba35c066fe7388f4d8217', max_length=128),
        ),
    ]
