# Generated by Django 3.1.3 on 2021-02-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210214_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x1bfb40873fb7df89a8ad1e3848d46f26', max_length=128),
        ),
    ]
