# Generated by Django 3.1.3 on 2021-02-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210214_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x4cc13155852b698f5eb80ee7ec021824', max_length=128),
        ),
    ]
