# Generated by Django 3.1.3 on 2021-02-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210215_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xa90c6c34c38b1454e01f6964ea1997c1', max_length=128),
        ),
    ]
