# Generated by Django 3.1.3 on 2021-02-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210219_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x47372776227ea6a8f339de6c73676389', max_length=128),
        ),
    ]
