# Generated by Django 3.1.3 on 2021-02-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210219_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x4270da118360daf7b7097075567dc04e', max_length=128),
        ),
    ]
