# Generated by Django 3.1.3 on 2021-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210222_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x486cdf8552ef21f3bcfbe08743695515', max_length=128),
        ),
    ]
