# Generated by Django 3.1.3 on 2021-02-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210222_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x6f5c16761a4cde1f3c0d598cbc83b380', max_length=128),
        ),
    ]
