# Generated by Django 3.1.3 on 2021-02-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210222_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x2473a6de7c9d23182466da3989a03281', max_length=128),
        ),
    ]
