# Generated by Django 3.1.3 on 2021-02-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210222_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x3fdae7641b4ca991d1bf5cff41bd1237', max_length=128),
        ),
    ]
