# Generated by Django 3.1.3 on 2021-02-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210226_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x4722f20fe62ddbf5028a8f83babdf04d', max_length=128),
        ),
    ]
